name: wally_the_stupid
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.0.0 #use only when necessary

  cupertino_icons: ^1.0.4
  animated_text_kit: any
  feature_discovery: any
  flutter_launcher_icons: any

  shared_preferences: any
  url_launcher: any
  path_provider: any
  fluttertoast: any
  salomon_bottom_bar: any
  google_mobile_ads: any
  workmanager: any
  flutter_local_notifications: any
  cron: any

  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  firebase_storage: any
  cloud_firestore: any
  package_info_plus: any
  get: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#11948C"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  